### ISSUE TITLE
Add antibody support

### ISSUE THREAD

**Issue by jsparedes** [eendroroy/zed-zsh#1]
As complement, you can add installation for [antibody](http://getantibody.github.io/)

`antibody bundle eendroroy/zed-zsh`

**Comment by eendroroy** [comment]
Did you try to install using antibody? What happens if try it?

**Comment by jsparedes** [comment]
I don't know why but It works :open_mouth:   
![z_antibody](https://user-images.githubusercontent.com/697562/42612996-1790e9fe-8564-11e8-87b3-a9b53fb9d8a0.gif)

**Comment by eendroroy** [comment]
awesome  :)
👍
